/*
 * generated by Xtext
 */
package com.github.jmodel.validation.plugin.ui.outline

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider


/**
 * Customization of the default outline structure.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
class ValidationLanguageOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
