/*
 * generated by Xtext
 */
package com.github.jmodel.validation.plugin.ui.contentassist


/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ValidationLanguageProposalProvider extends AbstractValidationLanguageProposalProvider {
}
