/*
 * generated by Xtext
 */
package com.github.jmodel.validation.plugin.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ValidationLanguageUiModule extends com.github.jmodel.validation.plugin.ui.AbstractValidationLanguageUiModule {
	public ValidationLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
