/*
* generated by Xtext
*/
package com.github.jmodel.validation.plugin;

import com.github.jmodel.validation.plugin.ValidationLanguageStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ValidationLanguageStandaloneSetup extends ValidationLanguageStandaloneSetupGenerated{

	public static void doSetup() {
		new ValidationLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

